# Project: Project1
# Makefile created by Dev-C++ 5.6.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = D:/Devc++/Dev-Cpp/MinGW32/lib/main.o acllib.o
LINKOBJ  = D:/Devc++/Dev-Cpp/MinGW32/lib/main.o acllib.o
LIBS     = -L"D:/Devc++/Dev-Cpp/MinGW32/lib" -L"D:/Devc++/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows D:/Devc++/Dev-Cpp/MinGW32/lib/libwinmm.a D:/Devc++/Dev-Cpp/MinGW32/lib/libmsimg32.a D:/Devc++/Dev-Cpp/MinGW32/lib/libkernel32.a D:/Devc++/Dev-Cpp/MinGW32/lib/libuser32.a D:/Devc++/Dev-Cpp/MinGW32/lib/libgdi32.a D:/Devc++/Dev-Cpp/MinGW32/lib/libole32.a D:/Devc++/Dev-Cpp/MinGW32/lib/liboleaut32.a D:/Devc++/Dev-Cpp/MinGW32/lib/libuuid.a -g3
INCS     = -I"D:/Devc++/Dev-Cpp/MinGW32/include" -I"D:/Devc++/Dev-Cpp/MinGW32/mingw32/include" -I"D:/Devc++/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"D:/Devc++/Dev-Cpp/MinGW32/include" -I"D:/Devc++/Dev-Cpp/MinGW32/mingw32/include" -I"D:/Devc++/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"D:/Devc++/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = bg.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

D:/Devc++/Dev-Cpp/MinGW32/lib/main.o: D:/Devc++/Dev-Cpp/MinGW32/lib/main.cpp
	$(CPP) -c D:/Devc++/Dev-Cpp/MinGW32/lib/main.cpp -o D:/Devc++/Dev-Cpp/MinGW32/lib/main.o $(CXXFLAGS)

acllib.o: acllib.c
	$(CPP) -c acllib.c -o acllib.o $(CXXFLAGS)
